CREATE DATABASE EDUHOME
USE EDUHOME
CREATE TABLE EVENTS
(
ID INT  PRIMARY KEY IDENTITY,
NAME NVARCHAR(200) NOT NULL,
[DESC] NVARCHAR(200) ,
ADRESS NVARCHAR(200) ,
STARTDATE DATE ,
STARTTIME TIME ,
ENDTIME TIME
)
CREATE TABLE SPEAKERS
(
ID INT  PRIMARY KEY IDENTITY,
FULLNAME NVARCHAR(200) NOT NULL,
POSITION NVARCHAR(200) ,
COMPANY NVARCHAR(200) ,
IMAGEURL NVARCHAR(200) ,
)
CREATE TABLE EVENTSSPEAKERS
(
EVENTID INT FOREIGN KEY REFERENCES EVENTS(ID),
SPEAKERID INT FOREIGN KEY REFERENCES SPEAKERS(ID)
)
SELECT * from events

SELECT * from SPEAKERS

SELECT * from EVENTSSPEAKERS